version: '3.4'

services: 

    data-base:
        container_name: db
        image: mariadb
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=sa
            - MYSQL_USER=yuri
            - MYSQL_PASSWORD=123456
        ports: 
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql/data      
            
volumes:
    db-data: